Consider the linear subspace S = spanfv1; v2; v3; v4g where v1 = [1; 2; 3; 4]; v2 = [0; 1; 0; 1]; v3 =
[1; 4; 3; 6]; v4 = [2; 11; 6; 15]. Create a vector inside S dierent from v1; v2; v3; v4. Create a
vector not in S. How would you check if a new vector is in S?

In [46]:
import numpy as np
import sympy 
import scipy.linalg
from scipy.optimize import minimize

In [5]:
s=np.array([[1,0,1,2],[2,1,4,11],[3,0,3,6],[4,1,6,15]])

In [6]:
s

array([[ 1,  0,  1,  2],
       [ 2,  1,  4, 11],
       [ 3,  0,  3,  6],
       [ 4,  1,  6, 15]])

In [8]:
y = np.linalg.det(s)
y

# determinant is 0, so we can not take an inverse of s

0.0

In [13]:
sympy.Matrix(s).rref()

(Matrix([
 [1, 0, 1, 2],
 [0, 1, 2, 7],
 [0, 0, 0, 0],
 [0, 0, 0, 0]]), (0, 1))

In [ ]:
# therefore, a linear combination of vectors v1 and v2 will give us a vector in the subspace S
# v1+v2= [1,3,3,5] this vector lies in the subspace S

In [16]:
n=np.dot(s,[3,6,8,10])
n
#n also lies in the subspace S

array([ 31, 154,  93, 216])

Find the dimension of the subspace S.

In [45]:
sympy.Matrix(s).rref()

(Matrix([
 [1, 0, 1, 2],
 [0, 1, 2, 7],
 [0, 0, 0, 0],
 [0, 0, 0, 0]]), (0, 1))

In [18]:
# dimension of the subspace S is 2 that is, (0,1) or (v1,v2) as seen in the output of cell above

Find an orthonormal basis for the subspace S.

In [39]:
# making sure that v1 and v2 are not orthogonal, i.e v1.v2!=0

np.dot([1,2,3,4],[0,1,0,1])

6

In [40]:
# orthonormal basis in given by:

scipy.linalg.orth(s)

array([[-0.1098991 ,  0.2669373 ],
       [-0.54396107, -0.53613402],
       [-0.32969731,  0.80081189],
       [-0.76375927, -0.00225943]])

In [41]:
# verification

v11=scipy.linalg.orth(s)[:,0]
v12=scipy.linalg.orth(s)[:,1]
print(v11,v12)

[-0.1098991  -0.54396107 -0.32969731 -0.76375927] [ 0.2669373  -0.53613402  0.80081189 -0.00225943]


In [42]:
# this should be equal to 0 for perfect orthonormality

np.dot(v11,v12)

2.220446049250313e-16

Solve the optimization problem minx2Sjjx 􀀀 zjj2 where z = [1; 0; 0; 0].

In [43]:
z=np.array([1,0,0,0])
z

array([1, 0, 0, 0])

In [94]:
# http://mathworld.wolfram.com/MatrixNorm.html

def fun(r):
    s=np.array([[1,0,1,2],[2,1,4,11],[3,0,3,6],[4,1,6,15]])
    z=np.array([1,0,0,0])
    v=np.dot(s,r)
    m=v-z
    y = m.conj().T
    n=np.dot(m,y)
    #b=scipy.linalg.eigh(n) not needed since eigenvalue of a 1x1 is equal to the only element present
    c=sqrt(n)
    return c

In [95]:
initial_guess = [1, 1, 1, 1]
result = scipy.optimize.minimize(fun, initial_guess)

In [96]:
# vector x for which the given problem has a minimum solution:

np.dot(s,result.x)

array([ 0.08333338, -0.08333352,  0.25000013,  0.08333323])

Is there a relation of this optimization problem with linear regression? Discuss.

In [77]:
# The minimization problem looks like a possible loss function of a linear rergession model. z* can be the set of known values of the dependent variables. And the x can be the product of betas and the independent variables. Instead of minimizing the mean squared error, in this problem we are minimizing the spectral norm of the difference between z* and x, which would give us a new set of betas if this was a regression problem.